name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install and Test
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm test
